name: Validator
# This workflow is triggered on pushes to the repository.
on: [push, pull_request, issues]

jobs:
  fmt:
    name: Code Format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - run: |
          terraform fmt --recursive -check=true

  docs:
    name: Pre-Commit-Hook
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Deps
        run: |
          brew install pre-commit terraform-docs terraform tflint
      - name: Check All Files
        run: |
          pre-commit run --all-files

  minimum:
    name: Minimum version check
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:0.12.9
    steps:
      - uses: actions/checkout@master
      - name: Validate Code
        env:
          TF_WARN_OUTPUT_ERRORS: 1
        run: |
          cat > provider.tf <<~EOS
          provider "aws" {
            region  = "us-west-1"
          }
          EOS
          terraform init
          terraform validate -var "alias_name=test"
